apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp
  labels:
    app.kubernetes.io/name: sampleapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sampleapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sampleapp
    spec:
      containers:
      - name: sampleapp
        image: replicity/gitops-sampleapp:daf78924f815cf9d4d920d4fa1ed23a2aa188a25
        ports:
          - containerPort: 80
