apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-sampleapp
  namespace: argocd
spec:
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc # Argo CDがインストールされているk8s自身
  source: # デプロイするマニフェスト
    path: manifest/sampleapp/overlays/dev
    repoURL:  https://github.com/replu/gitops-manifest # マニフェストリポジトリ
    targetRevision: dev # 開発環境用ブランチ
